# Generated by Django 4.1 on 2022-09-11 05:38

from django.db import migrations, models
import web_server.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[web_server.core.validators.validate_cnpf], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=11, validators=[web_server.core.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
