# Generated by Django 4.1.1 on 2022-10-16 03:44

import django.core.validators
from django.db import migrations, models

import web_server.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_email_verified_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(
                max_length=150,
                validators=[
                    web_server.core.validators.validate_name_is_alpha,
                    django.core.validators.MinLengthValidator(3),
                ],
                verbose_name='Name',
            ),
        ),
    ]
