# Generated by Django 4.1.3 on 2022-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sent_verification_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_email_secret',
            field=models.TextField(default=None, null=True),
        ),
    ]
