# Generated by Django 4.1.4 on 2022-12-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_sent_verification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_secret',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sent_reset_password_email',
            field=models.BooleanField(default=False),
        ),
    ]
