# Generated by Django 4.1.4 on 2023-01-16 03:08

from django.db import migrations, models

import web_server.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(
                blank=True,
                default='',
                max_length=14,
                validators=[web_server.core.validators.validate_cnpj],
                verbose_name='CNPJ',
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(
                blank=True,
                default='',
                max_length=11,
                validators=[web_server.core.validators.validate_cpf],
                verbose_name='CPF',
            ),
        ),
    ]
