# Generated by Django 4.1.6 on 2023-02-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Isotope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('name', models.CharField(max_length=6, unique=True)),
                ('dosimetry', models.BooleanField(default=False)),
                ('radiosyno', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Isotope for dosimetry',
                'verbose_name_plural': 'Isotopes for dosimetry',
                'ordering': ['-created_at'],
            },
        ),
    ]
