# Generated by Django 4.1.6 on 2023-02-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isotope', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isotope',
            options={'ordering': ['-created_at'], 'verbose_name': 'Isotope', 'verbose_name_plural': 'Isotopes'},
        ),
    ]
