# Generated by Django 4.1.9 on 2026-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isotope', '0002_alter_isotope_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='isotope',
            name='pet',
            field=models.BooleanField(default=False),
        ),
    ]
