FROM python:3.8.16-alpine3.17

ARG USER_DIR=/user/app

# set work directory
WORKDIR $USER_DIR

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#
RUN apk add build-base

# copy project
COPY web_server/ web_server
COPY manage.py ./
COPY requirements.txt ./
COPY requirements-dev.txt ./
COPY tox.ini ./

# install dependencies
RUN pip install --upgrade pip
RUN pip install pip-tools
RUN pip-sync requirements.txt requirements-dev.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
