services:

  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    container_name: dosimagem_api_dev
    image: dosimagem-dev/api:v1
    environment:
      - DATABASE_URL=postgres://dosimagem:dosimagem@database/dosimagem_db
      - ALLOWED_HOSTS=*
    restart: 'no'
    env_file:
      - .env
    networks:
      - dosimagem_nw
    depends_on:
      - database
    volumes:
      - ./staticfiles:/user/app/staticfiles
      - ./mediafiles:/user/app/mediafiles
    ports:
      - 8000:8000


  database:
    container_name: dosimagem_db
    image: postgres:14.5-alpine
    restart: 'no'
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=dosimagem
      - POSTGRES_USER=dosimagem
      - POSTGRES_DB=dosimagem_db
    networks:
      - dosimagem_nw
    ports:
      - 5434:5432

networks:
  dosimagem_nw:
    driver: bridge
