FROM python:3.8.16-slim-buster

ARG USER_DIR=/user/app

# set work directory
WORKDIR $USER_DIR

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# RUN apt-get update && apt-get install -y\
#     libpq-dev\
#     gcc\
#     && rm -rf /var/lib/apt/lists/*

# copy project
COPY web_server/ web_server
COPY manage.py requirements.txt requirements-dev.txt tox.ini ./

# install dependencies
RUN pip install -U pip &&\
    pip install --no-cache-dir -r requirements.txt &&\
    pip install --no-cache-dir -r requirements-dev.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
