services:

  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: dosimagem_api
    image: dosimagem/api:v1
    restart: 'no'
    command: >
      wait-for-it database:5432 --timeout=20 -- bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn -b 0.0.0.0:9000 --workers=1 --threads=3 web_server.wsgi --access-logfile '-'"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://dosimagem:dosimagem@database:5432/dosimagem_db
    networks:
      - dosimagem_nw
    depends_on:
      - database
    volumes:
      - ./staticfiles:/user/app/staticfiles
      - ./mediafiles:/user/app/mediafiles

  database:
    container_name: dosimagem_db
    image: postgres:14.5-alpine
    restart: 'no'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=dosimagem
      - POSTGRES_USER=dosimagem
      - POSTGRES_DB=dosimagem_db
    networks:
      - dosimagem_nw
    ports:
      - 5434:5432

  nginx:
    container_name: dosimagem_nginx
    image: nginx:1.23.2-alpine
    networks:
      - dosimagem_nw
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./staticfiles:/var/www/site/staticfiles
    ports:
      - 80:80


networks:
  dosimagem_nw:
    driver: bridge

volumes:
  pgdata:
