# Generated by Django 4.1.4 on 2022-12-29 02:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('uri', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Price')),
                ('hired_period_init', models.DateField(blank=True, null=True)),
                ('hired_period_end', models.DateField(blank=True, null=True)),
                ('test_period_init', models.DateField(blank=True, null=True)),
                ('test_period_end', models.DateField(blank=True, null=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignatureBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signature.benefit')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signature.signature')),
            ],
            options={
                'ordering': ('signature', 'benefit'),
                'unique_together': {('benefit', 'signature')},
            },
        ),
        migrations.AddField(
            model_name='signature',
            name='benefits',
            field=models.ManyToManyField(
                related_name='signatures', through='signature.SignatureBenefit', to='signature.benefit'
            ),
        ),
        migrations.AddField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
