# Generated by Django 4.1.4 on 2022-12-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='hired_period_init',
            new_name='hired_period_initial',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='test_period_init',
            new_name='test_period_initial',
        ),
    ]
