# Generated by Django 4.1.7 on 2023-02-27 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='status_payment',
            field=models.CharField(
                choices=[('APG', 'Aguardando pagamento'), ('CON', 'Confirmado')],
                default='APG',
                max_length=3,
                verbose_name='Status payment',
            ),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=160, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='benefits',
            field=models.ManyToManyField(
                related_name='signatures',
                through='signature.SignatureBenefit',
                to='signature.benefit',
                verbose_name='Beneficio',
            ),
        ),
        migrations.AlterField(
            model_name='signature',
            name='hired_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='End of contract period'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='hired_period_initial',
            field=models.DateField(blank=True, null=True, verbose_name='Start of contracted period'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='plan',
            field=models.CharField(max_length=160, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='test_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='End of test period'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='test_period_initial',
            field=models.DateField(blank=True, null=True, verbose_name='Start of test period'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='signatures',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuario',
            ),
        ),
        migrations.AlterField(
            model_name='signaturebenefit',
            name='benefit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='signature.benefit', verbose_name='Beneficio'
            ),
        ),
        migrations.AlterField(
            model_name='signaturebenefit',
            name='signature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='signature.signature', verbose_name='Assinatura'
            ),
        ),
    ]
