# Generated by Django 3.2.13 on 2022-06-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import web_server.service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('description', models.TextField(max_length=2048, verbose_name='description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='unit price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], max_length=3, verbose_name='status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total price')),
                ('report', models.FileField(blank=True, upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'report'}), verbose_name='Report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('images', models.FileField(upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'img'}), verbose_name='Images')),
                ('observations', models.TextField(max_length=5000, verbose_name='Obeservations')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DosimetryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], max_length=3, verbose_name='status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total price')),
                ('report', models.FileField(blank=True, upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'report'}), verbose_name='Report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('C', 'Clinical'), ('P', 'Pre Clinical')], max_length=1, verbose_name='Dosimetry Type')),
                ('camera_factor', models.FloatField(verbose_name='Camera Factor')),
                ('radionuclide', models.CharField(max_length=6, verbose_name='Radionuclide')),
                ('injected_activity', models.FloatField(verbose_name='Injected Activity')),
                ('injection_datetime', models.DateTimeField(verbose_name='Injection datetime')),
                ('images', models.FileField(upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'img'}), verbose_name='Images')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputationalModelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], max_length=3, verbose_name='status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total price')),
                ('report', models.FileField(blank=True, upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'report'}), verbose_name='Report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('images', models.FileField(upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'img'}), verbose_name='Images')),
                ('equipment_specification', models.CharField(choices=[('C', 'CT'), ('S', 'SPECT')], max_length=1, verbose_name='Equipment Specification')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
