# Generated by Django 4.1 on 2022-09-01 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuota',
            new_name='Order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'User Order', 'verbose_name_plural': 'User Orders'},
        ),
    ]
