# Generated by Django 3.2.13 on 2022-06-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimetryorder',
            name='type',
            field=models.CharField(blank=True, choices=[('C', 'Clinical'), ('P', 'Pre Clinical')], max_length=1, verbose_name='Dosimetry Type'),
        ),
    ]
