# Generated by Django 3.2.13 on 2022-06-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info',
            new_name='order_id',
        ),
    ]
