# Generated by Django 3.2.13 on 2022-06-20 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_factor', models.FloatField(blank=True, null=True, verbose_name='Camera Factor')),
                ('radionuclide', models.CharField(blank=True, max_length=6, null=True, verbose_name='Radiocuclide')),
                ('injected_activity', models.FloatField(blank=True, null=True, verbose_name='Injeced Activity')),
                ('injection_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Injection datetime')),
                ('images', models.FileField(blank=True, null=True, upload_to='', verbose_name='Images')),
                ('obs', models.TextField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], max_length=3, verbose_name='status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.info')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
