# Generated by Django 4.1 on 2022-09-17 22:59

from django.db import migrations, models
import functools
import web_server.service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='images',
            field=models.FileField(upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'calibrations'}), verbose_name='Calibration Images'),
        ),
    ]
