# Generated by Django 4.1.4 on 2023-02-10 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsotopeRadiosyno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('name', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'radiosunoviorthesis Isotope',
                'verbose_name_plural': 'radiosunoviorthesis Isotopes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='radiosynoanalysis',
            name='isotope',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='radiosyno_analysis',
                to='service.isotoperadiosyno',
            ),
        ),
    ]
