# Generated by Django 4.1.7 on 2023-03-10 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='acquisition_time',
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name='Acquisition Time',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_name',
            field=models.CharField(
                choices=[
                    ('DC', 'Dosimetria Clínica'),
                    ('PCD', 'Dosimetria Pré-Clínica'),
                    ('SQ', 'Segmentação e Quantificação'),
                    ('RA', 'Radiosinoviortese'),
                ],
                max_length=3,
                verbose_name='Service name',
            ),
        ),
    ]
