# Generated by Django 3.2.14 on 2022-07-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_dosimetryorder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computationalmodelorder',
            name='status',
            field=models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], default='APG', max_length=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='dosimetryorder',
            name='status',
            field=models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], default='APG', max_length=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='segmentationorder',
            name='status',
            field=models.CharField(choices=[('APG', 'Aguardando pagamento'), ('APR', 'Aguardando processamento'), ('PRC', 'Processando'), ('CON', 'Concluído')], default='APG', max_length=3, verbose_name='status'),
        ),
    ]
