# Generated by Django 4.1 on 2022-09-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_userquota_order_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='quantity_of_analyzes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.AddField(
            model_name='order',
            name='permission',
            field=models.BooleanField(default=False, verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_of_analyzes',
            field=models.PositiveIntegerField(default=0, verbose_name='Remaning of analysis'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_name',
            field=models.CharField(choices=[('DC', 'Dosimetria Clinica'), ('DPC', 'Dosimetria Preclinica')], max_length=3, verbose_name='Service name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Price'),
        ),
    ]
