# Generated by Django 4.1 on 2022-09-19 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_alter_calibration_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreClinicDosimetryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('images', models.FileField(upload_to='', verbose_name='Images')),
                ('status', models.CharField(choices=[('AP', 'Analisando informações'), ('PR', 'Processando'), ('CO', 'Concluído')], default='AP', max_length=3, verbose_name='Status')),
                ('report', models.FileField(blank=True, null=True, upload_to='', verbose_name='Report')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preclinic_dosimetry_analysis', to='service.calibration')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preclinic_dosimetry_analysis', to='service.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preclinic_dosimetry_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preclinic_dosimetry_analyis',
            },
        ),
        migrations.CreateModel(
            name='ClinicDosimetryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('AP', 'Analisando informações'), ('PR', 'Processando'), ('CO', 'Concluído')], default='AP', max_length=3, verbose_name='Status')),
                ('report', models.FileField(blank=True, null=True, upload_to='', verbose_name='Report')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('images', models.FileField(upload_to='', verbose_name='Images')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_dosimetry_analysis', to='service.calibration')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_dosimetry_analysis', to='service.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_dosimetry_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_dosimetry_analyis',
            },
        ),
    ]
