# Generated by Django 3.2.13 on 2022-06-22 01:36

from django.db import migrations, models
import web_server.service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_info_info_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='info',
            name='images',
            field=models.FileField(blank=True, upload_to=web_server.service.models.upload_to, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='report',
            field=models.FileField(blank=True, upload_to=web_server.service.models.upload_to, verbose_name='Report'),
        ),
    ]
