# Generated by Django 4.1.9 on 2026-08-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isotope', '0002_alter_isotope_options'),
        ('service', '0002_alter_calibration_acquisition_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicdosimetryanalysis',
            name='isotope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='isotope.isotope'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment_modality',
            field=models.CharField(blank=True, choices=[('SPECT', 'SPECT'), ('SPECT_CT', 'SPECT/CT'), ('SPECT_MRI', 'SPECT/MRI'), ('PET', 'PET'), ('PET_CT', 'PET/CT'), ('PET_MRI', 'PET/MRI')], max_length=20, null=True, verbose_name='Equipment modality'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('SPECT', 'SPECT'), ('PET', 'PET')], max_length=10, null=True, verbose_name='Equipment type'),
        ),
        migrations.AddField(
            model_name='preclinicdosimetryanalysis',
            name='isotope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='isotope.isotope'),
        ),
        migrations.AlterField(
            model_name='clinicdosimetryanalysis',
            name='calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_dosimetry_analysis', to='service.calibration'),
        ),
    ]
