# Generated by Django 4.1.9 on 2026-09-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_clinicdosimetryanalysis_isotope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preclinicdosimetryanalysis',
            name='calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preclinic_dosimetry_analysis', to='service.calibration'),
        ),
    ]
