# Generated by Django 4.1 on 2022-10-01 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_clinicdosimetryanalysis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='calibration_name',
            field=models.CharField(
                max_length=24,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name='Calibration Name',
            ),
        ),
        migrations.AlterField(
            model_name='clinicdosimetryanalysis',
            name='analysis_name',
            field=models.CharField(
                max_length=24,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name='Analysis Name',
            ),
        ),
        migrations.AlterField(
            model_name='clinicdosimetryanalysis',
            name='status',
            field=models.CharField(
                choices=[
                    ('AI', 'Verificando informações'),
                    ('II', 'Informações inválidas'),
                    ('PR', 'Processando a análise'),
                    ('CO', 'Análise concluída'),
                ],
                default='AI',
                max_length=3,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='preclinicdosimetryanalysis',
            name='analysis_name',
            field=models.CharField(
                max_length=24,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name='Analysis Name',
            ),
        ),
        migrations.AlterField(
            model_name='preclinicdosimetryanalysis',
            name='status',
            field=models.CharField(
                choices=[
                    ('AI', 'Verificando informações'),
                    ('II', 'Informações inválidas'),
                    ('PR', 'Processando a análise'),
                    ('CO', 'Análise concluída'),
                ],
                default='AI',
                max_length=3,
                verbose_name='Status',
            ),
        ),
    ]
