# Generated by Django 4.1 on 2022-09-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_preclinicdosimetryanalysis_clinicdosimetryanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicdosimetryanalysis',
            options={'verbose_name': 'Clinic Dosimetry', 'verbose_name_plural': 'Clinic Dosimetries'},
        ),
        migrations.AlterModelOptions(
            name='preclinicdosimetryanalysis',
            options={'verbose_name': 'Preclinic Dosimetry', 'verbose_name_plural': 'Preclinic Dosimetries'},
        ),
    ]
