# Generated by Django 4.1.9 on 2026-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_preclinicdosimetryanalysis_calibration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment_modality',
            field=models.CharField(blank=True, choices=[('SPECT', 'SPECT'), ('SPECT_CT', 'SPECT/CT'), ('SPECT_MRI', 'SPECT/MRI'), ('PET', 'PET'), ('PET_CT', 'PET/CT'), ('PET_MRI', 'PET/MRI'), ('MICROSPECT_CT', 'microSPECT/CT'), ('MICROPET_CT', 'microPET/CT')], max_length=20, null=True, verbose_name='Equipment modality'),
        ),
    ]
