# Generated by Django 4.1 on 2022-10-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_calibration_calibration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
