# Generated by Django 4.1.1 on 2022-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicdosimetryanalysis',
            name='code',
            field=models.CharField(default='', max_length=30, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preclinicdosimetryanalysis',
            name='code',
            field=models.CharField(default='', max_length=30, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
