# Generated by Django 4.1 on 2022-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_calibration_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_payment',
            field=models.CharField(choices=[('APG', 'Aguardando pagamento'), ('CON', 'Confirmado')], default='APG', max_length=3, verbose_name='Status payment'),
        ),
    ]
