# Generated by Django 4.1 on 2022-09-04 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_calibration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calibration',
            unique_together={('user', 'calibration_name')},
        ),
    ]
