# Generated by Django 4.1.1 on 2022-10-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_clinicdosimetryanalysis_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clinicdosimetryanalysis',
            table='clinic_dosimetry_analysis',
        ),
        migrations.AlterModelTable(
            name='preclinicdosimetryanalysis',
            table='preclinic_dosimetry_analysis',
        ),
    ]
