# Generated by Django 4.1 on 2022-09-06 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_calibration_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='acquisition_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Acquisition Time'),
        ),
    ]
