# Generated by Django 4.1.1 on 2022-10-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_clinicdosimetryanalysis_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicdosimetryanalysis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preclinicdosimetryanalysis',
            name='user',
        ),
    ]
