# Generated by Django 4.1.1 on 2022-10-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_clinicdosimetryanalysis_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isotope',
            name='name',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
