# Generated by Django 4.1.1 on 2022-10-14 21:10

import functools
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import web_server.service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_isotope_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_name',
            field=models.CharField(
                choices=[
                    ('DC', 'Dosimetria Clinica'),
                    ('PCD', 'Dosimetria Preclinica'),
                    ('SQ', 'Segmentaçao e Quantificação'),
                ],
                max_length=3,
                verbose_name='Service name',
            ),
        ),
        migrations.CreateModel(
            name='SegmentationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificatioin Date and Time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'analysis_name',
                    models.CharField(
                        max_length=24,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name='Analysis Name',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('AI', 'Verificando informações'),
                            ('II', 'Informações inválidas'),
                            ('PR', 'Processando a análise'),
                            ('CO', 'Análise concluída'),
                        ],
                        default='AI',
                        max_length=3,
                        verbose_name='Status',
                    ),
                ),
                (
                    'report',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=functools.partial(web_server.service.models.upload_to, *(), **{'type': 'report'}),
                        verbose_name='Report',
                    ),
                ),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                (
                    'images',
                    models.FileField(
                        upload_to=functools.partial(
                            web_server.service.models.upload_to, *(), **{'type': 'segmentation_analysis'}
                        ),
                        verbose_name='Images',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='segmentation_analysis',
                        to='service.order',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Segmentation Analysis',
                'verbose_name_plural': 'Segmentation Analysis',
                'db_table': 'segmentation_analysis',
                'unique_together': {('order', 'analysis_name')},
            },
        ),
    ]
