# Generated by Django 4.1.1 on 2022-10-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_clinicdosimetryanalysis_message_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicdosimetryanalysis',
            name='status',
            field=models.CharField(
                choices=[
                    ('DS', 'Dados enviados'),
                    ('AI', 'Verificando informações'),
                    ('II', 'Informações inválidas'),
                    ('PR', 'Processando a análise'),
                    ('CO', 'Análise concluída'),
                ],
                default='DS',
                max_length=3,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='preclinicdosimetryanalysis',
            name='status',
            field=models.CharField(
                choices=[
                    ('DS', 'Dados enviados'),
                    ('AI', 'Verificando informações'),
                    ('II', 'Informações inválidas'),
                    ('PR', 'Processando a análise'),
                    ('CO', 'Análise concluída'),
                ],
                default='DS',
                max_length=3,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='segmentationanalysis',
            name='status',
            field=models.CharField(
                choices=[
                    ('DS', 'Dados enviados'),
                    ('AI', 'Verificando informações'),
                    ('II', 'Informações inválidas'),
                    ('PR', 'Processando a análise'),
                    ('CO', 'Análise concluída'),
                ],
                default='DS',
                max_length=3,
                verbose_name='Status',
            ),
        ),
    ]
