# Generated by Django 4.1.1 on 2022-10-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_clinicdosimetryanalysis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicdosimetryanalysis',
            name='message_to_user',
            field=models.TextField(blank=True, default='', verbose_name='Message to user'),
        ),
        migrations.AlterField(
            model_name='preclinicdosimetryanalysis',
            name='message_to_user',
            field=models.TextField(blank=True, default='', verbose_name='Message to user'),
        ),
        migrations.AlterField(
            model_name='segmentationanalysis',
            name='message_to_user',
            field=models.TextField(blank=True, default='', verbose_name='Message to user'),
        ),
    ]
