# Generated by Django 4.1.1 on 2022-10-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_clinicdosimetryanalysis_message_to_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clinicdosimetryanalysis',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Clinic Dosimetry',
                'verbose_name_plural': 'Clinic Dosimetries',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='preclinicdosimetryanalysis',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Preclinic Dosimetry',
                'verbose_name_plural': 'Preclinic Dosimetries',
            },
        ),
        migrations.AlterModelOptions(
            name='segmentationanalysis',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Segmentation Analysis',
                'verbose_name_plural': 'Segmentation Analysis',
            },
        ),
    ]
