# Generated by Django 4.1.3 on 2022-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_segmentationanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_name',
            field=models.CharField(
                choices=[
                    ('DC', 'Dosimetria Clínica'),
                    ('PCD', 'Dosimetria Pré-Clínica'),
                    ('SQ', 'Segmentação e Quantificação'),
                    ('RA', 'Radiosinoviortese'),
                    ('MC', 'Modelagem Computacional'),
                ],
                max_length=3,
                verbose_name='Service name',
            ),
        ),
    ]
