# Generated by Django 4.1.4 on 2023-01-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_order_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='permission',
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
