services:

  database:
    container_name: dosimagem_db
    image: postgres:14.5-alpine
    restart: 'no'
    volumes:
      - ../../db/pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=dosimagem
      - POSTGRES_USER=dosimagem
      - POSTGRES_DB=dosimagem_db
    networks:
      - dosimagem_nw
    ports:
      - 5432

  api:
    build:
      dockerfile: docker/api-dev.dockerfile
      context: ../../
    volumes:
      - ../../contrib:/user/app/contrib/
    container_name: dosimagem_api
    image: dosimagem/api:v1
    restart: 'no'
    env_file:
      - ../../.env
    ports:
      - 8000:8000
    networks:
      - dosimagem_nw
    depends_on:
      - database

networks:
  dosimagem_nw:
    driver: bridge
